sudo: required

services:
    - docker

before_install:
    - docker build -t dezbah/dockertest -f Dockerfile.dev .

script:
    - docker run -e CI=true dezbah/dockertest npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-832999669948"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
