sudo: required

services:
    - docker

before_install:
    - npm install -g npm@latest
    - npm install -g aws-cli

install:
    - npm install

before_deploy:
    # Build Docker Compose file
    - docker-compose build

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-832999669948"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
