name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      -  master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
         logout: true

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dezbah/react-app:${{ github.sha }}

      - name: Deploy to Elastic Beanstalk
        uses: dezbah/react-app:${{ github.sha }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: your-elastic-beanstalk-application-name
          environment_name: your-elastic-beanstalk-environment-name
          version_label: ${{ github.sha }}
          region: "eu-west-1"
          bucket_name: "elasticbeanstalk-eu-west-1-832999669948"
          key_name: "docker"
          docker_image: dezbah/react-app:${{ github.sha }}
